### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by mtelvers**
I inadvertently pushed my last commit to master.

This commit updates the test results to work with the latest ocaml-dockerfile submodule.

### CODE REVIEW

**Comment by shonfeder** [comment]
Looks like another promotion is needed to satisfy the linting check: https://ocaml.ci.dev/github/ocurrent/opam-repo-ci/commit/edca6c4ba1a15f49da22c5d7eff19b0fa785a454/variant/%28lint-doc%29#L1028-1028

**Comment by punchagan** [comment]
Looks like the change to deprecate Ubuntu 23.10 in https://github.com/ocurrent/ocaml-dockerfile/pull/214 which is due to be merged next week is already a part of the submodule on master. Do we want to revert it? Or are we okay to deprecate the OS a week earlier?

**Comment by mtelvers** [comment]
I'm happy to deprecate it a week early so save an extra redeployment.

**Review by punchagan — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
