### PR TITLE
Add support for s390x testing for packages.

### PR DESCRIPTION
**Pull request by tmcgilchrist**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
i thought the capacity of the s390x machines were rather small. Do you have the numbers on hand?

**Comment by talex5** [comment]
We've got 4 (fast) cores, so at least twice as much as we've got for mac builds.

**Comment by kit-ty-kate** [comment]
the difference is that macos doesn't compete with the other services (ocaml-ci and docker-base-images). But I guess we'll try

**Comment by kit-ty-kate** [comment]
This PR also does the following changes:
* Add OpenSUSE 15.3
* Remove Ubuntu 20.10

All in all, it looks good now. Let's test this. Thanks!

**Pull request merged**
