### PR TITLE
Add a new lint check: disallow the extra-files field in opam packages

### PR DESCRIPTION
**Pull request by hannesm**
There's a great alternative - extra-sources - that should be used instead.

The motivation is https://github.com/ocaml/opam-repository/issues/25876, and this PR should be merged and put live once opam-repository is in the new state. I'll comment once this is the case.

I open this PR for (a) CI run (b) review, and (c) tracking the progress of https://github.com/ocaml/opam-repository/issues/25876

### CODE REVIEW

**Review by benmandrew — APPROVED** [review]
PR technically looks good. We'll wait to see feedback from the `opam-repository` issue before merging.

**Comment by shonfeder** [comment]
We talked about https://github.com/ocaml/opam-repository/issues/25876 in the opam repo maintainer meeting yesterday, and the maintenance team was all in favor. I've asked them to make the approval explicit on the issue. But iiuc, we want to be sure to wait to merge this until after the changes go in effect on the opam-repository, so we'll wait to hear from you, @hannesm. Thanks :)

**Comment by shonfeder** [comment]
I'm going to convert this to a draft, just as an indicator to us that is not waiting to be merged.

**Comment by hannesm** [comment]
This should now be merged and pushed to live.

**Pull request merged**
