### PR TITLE
Set revdeps jobs as non-urgent

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Review by talex5 — COMMENTED** [review]
Putting this in value does mean it will have to rebuild all the jobs for the new urgency level.

I suggest either putting this in `t` (next to the timeout setting), or just calculating it from `spec` (i.e. use urgent=false if the build's revdep = None, otherwise use the priority).

Note that a job should only be urgent if it's not a revdep **and** it's a high-priority OCurrent job. Otherwise, rebuilds due to e.g. opam-repository merges will be forced to be urgent too.

**Comment by avsm** [comment]
Needs a merge to resolve conflicts.

**Comment by talex5** [comment]
This is less important now that we have fair queuing - opam-repo-ci jobs won't block other users of the cluster. So the only benefit would be to make the revdeps of one PR lower priority than the main build of a later PR. We should probably revisit this later if that turns out to be a problem.

**Comment by kit-ty-kate** [comment]
Superseded by https://github.com/ocurrent/opam-repo-ci/pull/110

**Pull request closed without merging**
